In [7]:
import pandas as pd

Please replace file name: '/home/admin123/Downloads/final-paper/additional_data/data_test.csv' to one you want to check:)

## Help for test 5 

In [5]:
with open('/home/admin123/Downloads/final-paper/additional_data/data_test.csv') as foo:
    lines = len(foo.readlines())

Количество строк в файле:

In [42]:
lines

3

## Help for test 6

In [8]:
results = pd.read_csv('/home/admin123/Downloads/final-paper/additional_data/data_test.csv', header=None)

Датасет, который был прочитан из файла (строка отвечает за 1 строку в файле, каждое число это число в файле через запятую)

In [43]:
results

0      1      2      3      4      5      6      7      8      9      ...  \
0    832    134    128     31     62      6      0    144     32      8  ...   
1    832    134    128     31     62      6      0    144     32      8  ...   
2    768    134    128     31     62      6      0    144     32      8  ...   

   83840  83841  83842  83843  83844  83845  83846  83847  83848  83849  
0     69    160     32    148     68     70     85     68      0     91  
1     69    160     32    148     68     70     85     68      0     91  
2     69    160     32    148     68     70     85     68      0     91  

[3 rows x 83850 columns]

Размер датасета

In [13]:
results.shape

(3, 83850)

Размер датасета только с числами типа int

In [17]:
results.select_dtypes(include=['int64']).shape

(3, 83850)

## Help for test 7

In [18]:
results = pd.read_csv('/home/admin123/Downloads/final-paper/additional_data/data_test.csv', header=None)

Индексы и первое число в каждой из строк

In [44]:
results[0]

0    832
1    832
2    768
Name: 0, dtype: int64

## Help for test 8

In [28]:
results = pd.read_csv('/home/admin123/Downloads/final-paper/additional_data/data_test.csv', header=None)

Числа неравные 0 между на 2 строке (отсчет с 0), с позиции 768 до позиции 831 

In [46]:
results.iloc[2, 768:832][results.iloc[2, 768:832] != 0]

Series([], Name: 2, dtype: int64)

2 - строка для проверки, 768:832 - значения между которыии осущетвляется проверка на не 0

## Help for test 10

In [52]:
results = pd.read_csv('/home/admin123/Downloads/final-paper/additional_data/data_test.csv', header=None)

Индекс и второе число в каждой из строк

In [53]:
results[1] 

0    134
1    134
2    134
Name: 1, dtype: int64

## Help for test 11 and 12

In [54]:
results = pd.read_csv('/home/admin123/Downloads/final-paper/additional_data/data_test.csv', header=None)

Индексы и первое число в каждой из строк

In [55]:
results[0]

0    832
1    832
2    768
Name: 0, dtype: int64